### PR TITLE
add render-html protocol to allow user extensions

### LINKED ISSUE #12: Cannot display UUID's?
Hi.

This is a very neat library and will allow me to replace a less flexible alternative of my own. However I make a lot of use of #uuid objects (via cljs-uuid-utils) and it seems like these are tripping up the edn->hiccup converter.

I don't seem to use any special handling so I think it's just because they're not a recognised type in (render [v]) and getting rendered as a blank.

I made a quick patch adding:

(= t cljs.core/UUID) [:span.jh-type-string (str v)

and all seems well locally but I am not sure if it will work generally (i.e. without the cljs-uuid-utils library).

Perhaps there could be away to allow custom types to be rendered?

Thoughts?

m/

### PR DESCRIPTION
**Pull request by bensu**
This is the minimal change needed to fix #12 and allow users to define how their objects can be displayed. For example, to render `UUID`s, one would add:

```clj
(extend-protocol json-html.core/IRenderHTML
  cljs.core/UUID
  (render-html [u]
    [:span.jh-type-string (str u)]))
```

somewhere in the code and then simply call the existing api functions with an arbitrarily nested `UUID`.

Also, the new protocol has priority over the library defined render functions. So, if the user wants to redefine how `Keyword`s or `Set`s are rendered, extending the new protocol for those types also works.

### CODE REVIEW

**Comment by yogthos** [comment]
Thanks, would probably make sense to add this for the clj version as well.

**Comment by yogthos** [comment]
Just took a look, and looks like you can already extend the Render protocol in clj version, wouldn't it be better to use the same naming for cljs version then?

**Comment by yogthos** [comment]
Ok I did a bit of cleanup and pushed out a new version to Clojars `0.4.2`. I switched to use the existing `Render` protocol that was in the clj version.

**Comment by bensu** [comment]
Great! Thank you for pushing a new version so quickly. I thought about going `cljc` but I didn't want to send you a huge diff.

**Comment by yogthos** [comment]
No worries, thanks for getting the ball rolling. :)

**Pull request merged**
